spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    config:
      discovery:
        service-id: config-server
    gateway:
      routes:
        - id: organization-command
          uri: lb://ORGANIZATION-COMMAND
          predicates:
            - Path=/organization/**
            - Method=POST,PUT,PATCH,DELETE
          filters:
            - StripPrefix=1
        - id: organization-query
          uri: lb://ORGANIZATION-QUERY
          predicates:
            - Path=/organization/**
            - Method=GET
          filters:
            - StripPrefix=1

server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: always

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - gateway
          - metrics
